version: '3.8'

services:
  broker:
    image: redis:latest
    container_name: broker
    ports:
      - "6379:6379"
    volumes:
      - ./broker_data:/data
  redis-commander:
    image: rediscommander/redis-commander:latest
    environment:
      - REDIS_HOSTS=local:broker:6379
    ports:
      - "8081:8081"
    depends_on:
      - broker

volumes:
  broker_data: